### ISSUE TITLE
Redis::CannotConnectError: Timed out connecting to Redis

### ISSUE THREAD

**Issue by Pratibha-28** [pivotal-cf/cf-redis-release#47]
Sample redis application is not working, giving below error
Redis::CannotConnectError: Timed out connecting to Redis on --- broker-url:port---
Below is snap shot
![image](https://user-images.githubusercontent.com/19345296/30414334-a8359cea-9940-11e7-9f94-cdaa9de2663b.png)

Please suggest how to rectify the issue.

**Comment by alamages** [comment]
Hello @Pratibha-28,

Is this still a problem?

We don't have enough information to understand the issue fully.  

It seems that you have a redis sample app which is bound to a Redis shared-vm instance. The shared-vm instances run on the broker, thus your Redis endpoint is the broker url and the port is the port which your Redis instance is listening. 

Can you verify your service binding? If you run `cf services`, you should see a shared-vm instance bound to your app. If this is the case, you could manually try to access this Redis instance using a local redis client. In case you are not familiar you can do that by [creating a service-key](https://docs.cloudfoundry.org/devguide/services/service-keys.html) and using these credentials to connect to your Redis instance.

If everything is in place correctly (the shared-vm and its binding exists) and still not being able to access your Redis then it perhaps the problem is with the Redis process itself. In this case you could `bosh ssh` into `cf-redis-broker` and check if there is any process running that is listening to your Redis instance port.

Please let us know about any updates so we can give further advice.
